# Generated by Django 4.2.2 on 2023-07-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('screen', models.CharField(max_length=255)),
                ('RAM', models.CharField(max_length=255)),
                ('ROM', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
    ]
