# Generated by Django 4.2.2 on 2023-07-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('SHIPPING', 'Shipping'), ('ALREADY', 'Already')], default='PENDING', max_length=20),
        ),
    ]
