# Generated by Django 4.2.2 on 2023-07-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPING', 'Shipping'), ('ALREADY', 'Already')], default='PENDING', max_length=20),
        ),
    ]
