# Generated by Django 4.2.2 on 2023-07-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('NOTCLOSED', 'Not closed'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPING', 'Shipping'), ('ALREADY', 'Already')], default='NOTCLOSED', max_length=20),
        ),
    ]
