# Generated by Django 4.2.2 on 2023-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_int',
            field=models.IntegerField(default=0),
        ),
    ]
