# Generated by Django 4.2.2 on 2023-07-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_price_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_int',
            field=models.IntegerField(),
        ),
    ]
